### PR TITLE
Add home-away filter to get_league_table

### PR DESCRIPTION
**Pull request by ChrisMusson**

### CODE REVIEW

**Comment by amosbastian** [comment]
Maybe add which value to use for home and away respectively to the docstring? I'll most likely merge it once I'm back from holiday (next Sunday or the Saturday after that)

**Comment by svenngronbeck** [comment]
Any chance this gets merged soon?

**Comment by amosbastian** [comment]
> Any chance this gets merged soon?

Sorry I completely forgot about this! Will merge it this afternoon

**Comment by amosbastian** [comment]
It should be released now @svenngronbeck

**Pull request merged**
