### PR TITLE
Remove reliance on bs4 and regex to parse html

### PR DESCRIPTION
**Pull request by rasoolsomji**
Potential improvement for #4 

It's hard to test if or how much it has sped up, I think my test suite is running fractionally faster, but all other online benchmark tools I've seen rate regex and BeautifulSoup as slower than the method I've used here.

All tests pass (except for test_get_league_fixtures_with_options() since there are no unplayed fixtures in the 2018 season)

### CODE REVIEW

**Comment by amosbastian** [comment]
Thanks, will look into it once I get back from holiday in roughly two weeks.

**Comment by amosbastian** [comment]
Sorry for taking so long getting back to you. Checking the CI and testing it locally I seem to get an error when trying it out:

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rasoolsomji** [comment]
No worries! I happen to be away myself now for the next couple of weeks but
I'll take a look when I'm back

**Comment by rasoolsomji** [comment]
@amosbastian I am honestly not sure... are you getting that error message on any particular test?

**Comment by amosbastian** [comment]
Basically all the tests fail for me locally, same for Travis CI. Only thing I can think of that could be causing it is the operating system. I'm on Ubuntu, what about you?

**Comment by rasoolsomji** [comment]
Yup same, Ubuntu 16.04, and Python 3.6.8.  I'm baffled.

What happens if you manually try to make the changes I made in utils.py to a new local branch?  That's the only file I significantly changed

**Comment by amosbastian** [comment]
Same thing happens. It's really confusing and everything I find about it on StackOverflow and so one doesn't solve it. Not sure what we should do next, haha.

**Comment by rasoolsomji** [comment]
Haha me neither, I guess it's just one of those things.  Maybe let's leave it a while and come back to it, it might have sorted itself out

**Pull request closed without merging**
